# 基础镜像
FROM redis
# author
MAINTAINER cloud

# 挂载目录
VOLUME /home/cloud/redis
# 创建目录
RUN mkdir -p /home/cloud/redis
# 指定路径
WORKDIR /home/cloud/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/cloud/redis/redis.conf
