version : '3.8'
services:
  cloud-nacos:
    container_name: cloud-nacos
    image: nacos/nacos-server
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - cloud-mysql
  cloud-mysql:
    container_name: cloud-mysql
    image: mysql:8.0
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    environment:
      MYSQL_DATABASE: ai-cloud
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_HOST: '%'
      MYSQL_INITDB_SKIP_TZINFO: "Asia/Shanghai"
  cloud-redis:
    container_name: cloud-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/cloud/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/cloud/redis/redis.conf
  cloud-nginx:
    container_name: cloud-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html/cloud-admin:/home/cloud/cloud-admin
      - ./nginx/html/cloud-mobile:/home/cloud/cloud-mobile
      - ./nginx/crt:/home/cloud/crt
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - ai-cloud-gateway
    links:
      - ai-cloud-gateway
  ai-cloud-gateway:
    container_name: ai-cloud-gateway
    build:
      context: ./cloud/gateway
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - cloud-redis
    links:
      - cloud-redis
  ai-cloud-auth:
    container_name: ai-cloud-auth
    build:
      context: ./cloud/auth
      dockerfile: dockerfile
    ports:
      - "9200:9200"
    depends_on:
      - cloud-redis
    links:
      - cloud-redis
  ai-cloud-system:
    container_name: ai-cloud-system
    build:
      context: ./cloud/modules/system
      dockerfile: dockerfile
    ports:
      - "9201:9201"
    depends_on:
      - cloud-redis
      - cloud-mysql
    links:
      - cloud-redis
      - cloud-mysql
  ai-cloud-gen:
    container_name: ai-cloud-gen
    build:
      context: ./cloud/modules/gen
      dockerfile: dockerfile
    ports:
      - "9202:9202"
    depends_on:
      - cloud-mysql
    links:
      - cloud-mysql
  ai-cloud-job:
    container_name: ai-cloud-job
    build:
      context: ./cloud/modules/job
      dockerfile: dockerfile
    ports:
      - "9203:9203"
    depends_on:
      - cloud-mysql
    links:
      - cloud-mysql
  ai-cloud-file:
    container_name: ai-cloud-file
    build:
      context: ./cloud/modules/file
      dockerfile: dockerfile
    ports:
      - "9300:9300"
    volumes:
    - ./cloud/uploadPath:/home/cloud/uploadPath
  ai-cloud-monitor:
    container_name: ai-cloud-monitor
    build:
      context: ./cloud/visual/monitor
      dockerfile: dockerfile
    ports:
      - "9100:9100"
  ai-cloud-user:
    container_name: ai-cloud-user
    build:
      context: ./cloud/app/user
      dockerfile: dockerfile
    ports:
      - "9401:9401"
    depends_on:
      - cloud-redis
      - cloud-mysql
    links:
      - cloud-redis
      - cloud-mysql
  ai-cloud-resource:
    container_name: ai-cloud-resource
    build:
      context: ./cloud/app/resource
      dockerfile: dockerfile
    ports:
      - "9403:9403"
    depends_on:
      - cloud-redis
      - cloud-mysql
    links:
      - cloud-redis
      - cloud-mysql
  ai-cloud-pay:
    container_name: ai-cloud-pay
    build:
      context: ./cloud/app/pay
      dockerfile: dockerfile
    ports:
      - "9402:9402"
    depends_on:
      - cloud-redis
      - cloud-mysql
    links:
      - cloud-redis
      - cloud-mysql
