# 基础镜像
FROM mysql:8.0
# author
MAINTAINER cloud

# 执行sql脚本
ADD ./db/*.sql /docker-entrypoint-initdb.d/

# 授权
# docker exec -it mysql /bin/bash
# mysql -u root -p
# grant all on *.* to 'root'@'%' with grant option;
# flush privileges
